name: Build Go Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod tidy

      - name: Build Linux executable
        run: GOOS=linux GOARCH=amd64 go build -o bin/Linux/datacalc main.go

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: datecalc
          path: bin/Linux/datecalc
